# This job runs the project tests

name: Daily build
on:
  workflow_dispatch:
  schedule:
  - cron: "0 5 * * *"

jobs:
  # This workflow contains a single job called "build"
  build-and-test-cron:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Run tests on MASTER branch
        if: ${{ github.ref == 'refs/heads/master' }}
        env:
          FBN_TOKEN_URL: ${{ secrets.DEVELOP_FBN_TOKEN_URL }}
          FBN_USERNAME: ${{ secrets.DEVELOP_FBN_USERNAME }}
          FBN_PASSWORD: ${{ secrets.DEVELOP_FBN_PASSWORD }}
          FBN_CLIENT_ID: ${{ secrets.DEVELOP_FBN_CLIENT_ID }}
          FBN_CLIENT_SECRET: ${{ secrets.DEVELOP_FBN_CLIENT_SECRET }}
          FBN_LUSID_API_URL: ${{ secrets.DEVELOP_FBN_LUSID_API_URL }}
          FBN_APP_NAME: ${{ secrets.DEVELOP_FBN_APP_NAME }}
        run: |
            echo "env variables have been set"

            version=$(date +"%Y%m%d%H%M%S")

            bash docker-setup.sh -n scheduler-job-example-python -v $version
